/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Submission = IDL.Record({
  'service' : IDL.Text,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'number' : IDL.Text,
});

export const idlService = IDL.Service({
  'addSubmission' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Submission = IDL.Record({
    'service' : IDL.Text,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'number' : IDL.Text,
  });
  
  return IDL.Service({
    'addSubmission' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };